[package]
name = "API"
version = "0.1.0"
edition = "2024"

[dependencies]
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
pretty_env_logger = "0.5"
uuid = { version = "1.0", features = ["v4"] }
log = "0.4"
